/* Functional browser tests use a synthetic camera, never a person's camera/microphone. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const copy=require('./localized-copy.cjs').load('browser.es.json');
const uiCopy=JSON.parse(fs.readFileSync(path.join(__dirname,'../frontend/public/locales/es.json'),'utf8'));
const output=path.resolve(__dirname,'../artifacts');fs.mkdirSync(output,{recursive:true});
const base=process.env.TEST_WEB_URL||'http://localhost:5173';
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.TEST_BROWSER_CHANNEL||'chrome',args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--autoplay-policy=no-user-gesture-required']});
 const errors=[];const results=[];let creator,viewer;
 function captureErrors(page){page.on('pageerror',e=>errors.push(e.message));}
 async function register(page,username){await page.getByRole('button',{name:copy.text("browserLabel003"),exact:true}).click();await page.getByRole('button',{name:copy.text("browserLabel004")}).click();await page.getByLabel(copy.text("browserLabel005"),{exact:true}).fill(username);await page.getByLabel(copy.text("browserLabel006")).fill(`${username}@example.com`);await page.getByLabel(copy.text("browserLabel007"),{exact:true}).fill('BrowserTest123!');await page.getByRole('checkbox').check();await page.getByRole('button',{name:copy.text("createAccount"),exact:true}).click();}
 try{
  const c=await browser.newContext({viewport:{width:1440,height:1040},permissions:['camera','microphone']});await c.addInitScript(()=>Object.defineProperty(navigator,'share',{value:undefined}));creator=await c.newPage();captureErrors(creator);await creator.goto(base);await creator.getByRole('heading',{name:copy.text("browserLabel008")}).waitFor();await creator.screenshot({path:path.join(output,'explore-desktop.png'),fullPage:true});assert.equal(await creator.title(),uiCopy.pageTitle);assert.equal(await creator.evaluate(()=>window.StreamMedia.messageForError(new DOMException('Permission denied','NotAllowedError'))),uiCopy.mediaPermissionDenied);results.push('Desktop loads the compiled TypeScript UI');
  const suffix=Date.now().toString(36);const creatorName=`creator_${suffix}`;await register(creator,creatorName);await creator.getByRole('heading',{name:copy.text("browserLabel009")}).waitFor();await creator.getByLabel(copy.text("browserLabel010"),{exact:true}).fill(copy.text("browserLabel011"));await creator.getByRole('button',{name:copy.text("browserLabel012"),exact:true}).click();await creator.getByRole('heading',{name:copy.text('creatorGreeting') + creatorName + ' ✦'}).waitFor();results.push('Registration, login and channel creation through TypeScript forms');
  await creator.getByRole('button',{name:copy.text("browserLabel013"),exact:true}).click();await creator.getByLabel(copy.text("restrictedWords"),{exact:true}).fill(copy.text("browserLabel014"));await creator.getByRole('button',{name:copy.text("browserLabel015"),exact:true}).click();await creator.getByRole('status').filter({hasText:copy.text("browserLabel016")}).waitFor();
  await creator.getByRole('button',{name:copy.text("myStudio"),exact:true}).click();await creator.getByLabel(copy.text("browserLabel017"),{exact:true}).fill(copy.text("browserLabel018"));await creator.getByRole('button',{name:copy.text("browserLabel019"),exact:true}).click();await creator.getByRole('button',{name:copy.text("browserLabel020"),exact:true}).waitFor({timeout:30000});await creator.waitForFunction(()=>document.querySelector('#live-video')?.srcObject?.getVideoTracks().length===1);await creator.screenshot({path:path.join(output,'studio-desktop.png'),fullPage:true});results.push('Synthetic camera and broadcaster signaling connect');
  const v=await browser.newContext({viewport:{width:1200,height:850}});viewer=await v.newPage();captureErrors(viewer);await viewer.goto(base);const viewerName=`viewer_${suffix}`;await register(viewer,viewerName);await viewer.getByRole('heading',{name:copy.text("browserLabel009")}).waitFor();await viewer.getByRole('button',{name:copy.text("explore"),exact:true}).click();await viewer.getByRole('button',{name:copy.text("browserLabel022"),exact:true}).first().click();
  await viewer.waitForFunction(()=>document.querySelector('#live-video')?.readyState>=2&&document.querySelector('#live-video')?.videoWidth>0,{},{timeout:30000});results.push('A second browser receives real WebRTC video');
  const chat=viewer.getByPlaceholder(copy.text("browserLabel023"));await chat.fill(copy.text("browserLabel024"));await viewer.getByRole('button',{name:copy.text("browserLabel025"),exact:true}).click();await creator.getByText(copy.text("browserLabel024"),{exact:true}).waitFor();results.push('Chat message is moderated, persisted and broadcast');
  await viewer.waitForTimeout(1100);await chat.fill(copy.text("browserLabel014"));await viewer.getByRole('button',{name:copy.text("browserLabel025"),exact:true}).click();await viewer.getByRole('status').filter({hasText:copy.text("browserLabel029")}).first().waitFor();assert.equal(await viewer.locator('.chat-list').getByText(copy.text("browserLabel014"),{exact:true}).count(),0);
  await creator.getByRole('button',{name:copy.text("browserLabel031"),exact:true}).click();await creator.locator('.quoted-message').getByText(copy.text("browserLabel014"),{exact:true}).waitFor();await creator.getByRole('button',{name:copy.text("browserLabel033"),exact:true}).click();await viewer.locator('.chat-list').getByText(copy.text("browserLabel014"),{exact:true}).waitFor();results.push('Restricted message stays private until human approval');
  await creator.getByRole('button',{name:copy.text("myStudio"),exact:true}).click();await creator.getByRole('button',{name:copy.text("browserLabel035"),exact:true}).click();await creator.getByRole('status').filter({hasText:copy.text("clipSavedPrefix")}).waitFor({timeout:55000});await creator.getByRole('button',{name:copy.text("browserLabel036"),exact:true}).click();await creator.getByRole('button',{name:copy.text("viewVideo"),exact:true}).first().click();await creator.waitForFunction(()=>document.querySelector('.clip-stage video')?.readyState>=2);await creator.getByRole('button',{name:copy.text("publishClip"),exact:true}).first().click();await creator.getByRole('status').filter({hasText:copy.text("clipPublished")}).waitFor();await creator.screenshot({path:path.join(output,'clips-desktop.png'),fullPage:true});results.push('MediaRecorder captures an actual playable clip and creator publishes it');
  await creator.getByRole('button',{name:uiCopy.uiClipCardText142,exact:true}).first().click();const editor=creator.getByRole('dialog');await editor.getByLabel(uiCopy.uiEditClipText147,{exact:true}).fill(copy.text('editedClipTitle'));await editor.getByLabel(uiCopy.trimEnd,{exact:true}).fill('1');await editor.getByRole('button',{name:uiCopy.saveChanges,exact:true}).click();await editor.waitFor({state:'hidden'});await creator.getByText(uiCopy.uiStatusNameText214,{exact:true}).first().waitFor();await creator.getByRole('button',{name:copy.text('viewVideo'),exact:true}).first().click();await creator.waitForFunction(()=>{const video=document.querySelector('.clip-stage video');return video?.readyState>=2&&video.duration>0&&video.duration<2;});await creator.getByRole('button',{name:copy.text('publishClip'),exact:true}).first().click();await creator.getByRole('status').filter({hasText:copy.text('clipPublished')}).waitFor();results.push('TypeScript clip editor trims video and requires a fresh approval');
  const downloaded=creator.waitForEvent('download');await creator.getByRole('button',{name:uiCopy.uiClipCardText141,exact:true}).first().click();const download=await downloaded;assert.match(download.suggestedFilename(),/\.webm$/);assert.equal(await download.failure(),null);await c.grantPermissions(['clipboard-read','clipboard-write']);await creator.getByRole('button',{name:uiCopy.uiClipCardText145,exact:true}).first().click();await creator.getByRole('status').filter({hasText:uiCopy.uiClipCardText146}).waitFor();const sharedUrl=await creator.evaluate(()=>navigator.clipboard.readText());assert(sharedUrl.startsWith(base+'/#clip='));const guest=await browser.newContext();const published=await guest.newPage();captureErrors(published);await published.goto(sharedUrl);await published.waitForFunction(()=>document.querySelector('.clip-stage video')?.readyState>=2);await guest.close();results.push('Clip download and shared public playback work without a session');
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});const phone=await mobile.newPage();captureErrors(phone);await phone.goto(base);await phone.getByRole('heading',{name:copy.text("browserLabel008")}).waitFor();assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await phone.screenshot({path:path.join(output,'explore-mobile.png'),fullPage:true});await phone.getByRole('button',{name:copy.text("browserLabel038"),exact:true}).click();await phone.getByRole('button',{name:copy.text("myStudio"),exact:true}).click();await phone.getByRole('heading',{name:copy.text("browserLabel039")}).waitFor();assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));results.push('390px mobile layout has no horizontal overflow and menu navigation works');
  await creator.getByRole('button',{name:copy.text("myStudio"),exact:true}).click();await creator.getByRole('button',{name:copy.text("browserLabel020"),exact:true}).click();await viewer.getByRole('status').filter({hasText:copy.text("browserLabel042")}).first().waitFor();results.push('Ending the stream notifies viewers and releases media');
  await creator.getByRole('button',{name:uiCopy.uiShellText12,exact:true}).click();await creator.getByRole('button',{name:uiCopy.uiAssistantText165,exact:true}).click();await creator.getByRole('status').filter({hasText:uiCopy.uiAssistantText166}).waitFor();await creator.locator('.summary-text').waitFor();await creator.getByRole('button',{name:uiCopy.uiShellText19,exact:true}).click();await creator.getByRole('dialog').waitFor();await creator.getByRole('button',{name:uiCopy.uiNotificationsText198,exact:true}).click();results.push('Assistant analysis and the native notification dialog work');
  await creator.getByRole('button',{name:uiCopy.myAccount,exact:true}).click();await creator.getByRole('button',{name:uiCopy.uiAccountText202,exact:true}).click();await creator.getByRole('button',{name:uiCopy.uiShellText18,exact:true}).click();await creator.getByLabel(uiCopy.uiAuthViewText46,{exact:true}).fill(`${creatorName}@example.com`);await creator.getByLabel(uiCopy.uiAuthViewText47,{exact:true}).fill('BrowserTest123!');await creator.getByRole('button',{name:uiCopy.signIn,exact:true}).click();await creator.getByRole('heading',{name:copy.text('creatorGreeting')+creatorName+' ✦'}).waitFor();await creator.reload();await creator.getByRole('button',{name:uiCopy.myAccount,exact:true}).waitFor();assert(await creator.evaluate(()=>Boolean(sessionStorage.getItem('streamguard.token'))));results.push('Logout, login and session restoration retain the API contract');
  assert.deepEqual(errors,[],'Browser JavaScript errors');fs.writeFileSync(path.join(output,'browser-test-results.json'),JSON.stringify({passed:true,results,errors},null,2));console.log(JSON.stringify({passed:true,results,errors},null,2));
 }catch(e){if(creator)await creator.screenshot({path:path.join(output,'browser-failure.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(output,'browser-test-results.json'),JSON.stringify({passed:false,results,errors,failure:e.message},null,2));throw e;}
 finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
