/* Functional browser tests use a synthetic camera, never a person's camera/microphone. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const output=path.resolve(__dirname,'../artifacts');fs.mkdirSync(output,{recursive:true});
const base=process.env.TEST_WEB_URL||'http://localhost:5173';
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.TEST_BROWSER_CHANNEL||'chrome',args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--autoplay-policy=no-user-gesture-required']});
 const errors=[];const results=[];let creator,viewer;
 function captureErrors(page){page.on('pageerror',e=>errors.push(e.message));}
 async function register(page,username){await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await page.getByRole('button',{name:'Quiero crear una cuenta'}).click();await page.getByLabel('Nombre de usuario',{exact:true}).fill(username);await page.getByLabel('Correo electrónico').fill(`${username}@example.com`);await page.getByLabel('Contraseña',{exact:true}).fill('BrowserTest123!');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Crear mi cuenta',exact:true}).click();}
 try{
  const c=await browser.newContext({viewport:{width:1440,height:1040},permissions:['camera','microphone']});creator=await c.newPage();captureErrors(creator);await creator.goto(base);await creator.getByRole('heading',{name:'Ahora en directo'}).waitFor();await creator.screenshot({path:path.join(output,'explorar-desktop.png'),fullPage:true});results.push('Desktop loads the compiled Java UI');
  const suffix=Date.now().toString(36);const creatorName=`creador_${suffix}`;await register(creator,creatorName);await creator.getByRole('heading',{name:'Dale un hogar a tu comunidad'}).waitFor();await creator.getByLabel('Nombre del canal',{exact:true}).fill('Comunidad QA · Prueba de streaming');await creator.getByRole('button',{name:'Crear canal',exact:true}).click();await creator.getByRole('heading',{name:`Hola, ${creatorName} ✦`}).waitFor();results.push('Registration, login and channel creation through Java forms');
  await creator.getByRole('button',{name:'Configuración',exact:true}).click();await creator.getByLabel('Palabras restringidas',{exact:true}).fill('palabra-prueba');await creator.getByRole('button',{name:'Guardar configuración',exact:true}).click();await creator.getByRole('status').filter({hasText:'Configuración guardada'}).waitFor();
  await creator.getByRole('button',{name:'Mi estudio',exact:true}).click();await creator.getByLabel('Título del directo',{exact:true}).fill('Laboratorio en vivo · Cámara sintética de pruebas');await creator.getByRole('button',{name:'Empezar transmisión  ↗',exact:true}).click();await creator.getByRole('button',{name:'Finalizar directo',exact:true}).waitFor({timeout:30000});await creator.waitForFunction(()=>document.querySelector('#live-video')?.srcObject?.getVideoTracks().length===1);await creator.screenshot({path:path.join(output,'estudio-desktop.png'),fullPage:true});results.push('Synthetic camera and broadcaster signaling connect');
  const v=await browser.newContext({viewport:{width:1200,height:850}});viewer=await v.newPage();captureErrors(viewer);await viewer.goto(base);const viewerName=`espectador_${suffix}`;await register(viewer,viewerName);await viewer.getByRole('heading',{name:'Dale un hogar a tu comunidad'}).waitFor();await viewer.getByRole('button',{name:'Explorar',exact:true}).click();await viewer.getByRole('button',{name:'Entrar al directo  →',exact:true}).filter({visible:true}).first().click();
  await viewer.waitForFunction(()=>document.querySelector('#live-video')?.readyState>=2&&document.querySelector('#live-video')?.videoWidth>0,{},{timeout:30000});results.push('A second browser receives real WebRTC video');
  const chat=viewer.getByPlaceholder('Comparte algo con la comunidad');await chat.fill('Hola desde la prueba del navegador');await viewer.getByRole('button',{name:'Enviar',exact:true}).click();await creator.getByText('Hola desde la prueba del navegador',{exact:true}).waitFor();results.push('Chat message is moderated, persisted and broadcast');
  await viewer.waitForTimeout(1100);await chat.fill('palabra-prueba');await viewer.getByRole('button',{name:'Enviar',exact:true}).click();await viewer.getByRole('status').filter({hasText:'Coincide con una palabra restringida'}).first().waitFor();assert.equal(await viewer.locator('.chat-list').getByText('palabra-prueba',{exact:true}).count(),0);
  await creator.getByRole('button',{name:'Moderación',exact:true}).click();await creator.locator('.quoted-message').getByText('palabra-prueba',{exact:true}).waitFor();await creator.getByRole('button',{name:'Permitir',exact:true}).click();await viewer.locator('.chat-list').getByText('palabra-prueba',{exact:true}).waitFor();results.push('Restricted message stays private until human approval');
  await creator.getByRole('button',{name:'Mi estudio',exact:true}).click();await creator.getByRole('button',{name:'Marcar momento',exact:true}).click();await creator.getByRole('status').filter({hasText:'Clip guardado.'}).waitFor({timeout:55000});await creator.getByRole('button',{name:'Biblioteca de clips',exact:true}).click();await creator.getByRole('button',{name:'Ver video',exact:true}).first().click();await creator.waitForFunction(()=>document.querySelector('.clip-stage video')?.readyState>=2);await creator.getByRole('button',{name:'Publicar',exact:true}).first().click();await creator.getByRole('status').filter({hasText:'Clip publicado'}).waitFor();await creator.screenshot({path:path.join(output,'clips-desktop.png'),fullPage:true});results.push('MediaRecorder captures an actual playable clip and creator publishes it');
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});const phone=await mobile.newPage();captureErrors(phone);await phone.goto(base);await phone.getByRole('heading',{name:'Ahora en directo'}).waitFor();assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await phone.screenshot({path:path.join(output,'explorar-mobile.png'),fullPage:true});await phone.getByRole('button',{name:'Mostrar menú',exact:true}).click();await phone.getByRole('button',{name:'Mi estudio',exact:true}).click();await phone.getByRole('heading',{name:'Qué bueno verte de nuevo'}).waitFor();assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));results.push('390px mobile layout has no horizontal overflow and menu navigation works');
  await creator.getByRole('button',{name:'Mi estudio',exact:true}).click();await creator.getByRole('button',{name:'Finalizar directo',exact:true}).click();await viewer.getByRole('status').filter({hasText:'La transmisión terminó'}).first().waitFor();results.push('Ending the stream notifies viewers and releases media');
  assert.deepEqual(errors,[],'Browser JavaScript errors');fs.writeFileSync(path.join(output,'browser-test-results.json'),JSON.stringify({passed:true,results,errors},null,2));console.log(JSON.stringify({passed:true,results,errors},null,2));
 }catch(e){if(creator)await creator.screenshot({path:path.join(output,'browser-failure.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(output,'browser-test-results.json'),JSON.stringify({passed:false,results,errors,failure:e.message},null,2));throw e;}
 finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
